### ISSUE TITLE
Serializing/Deserializing the `Entity` struct

### ISSUE THREAD

**Issue by Aceeri** [slide-rs/specs#138]
Some components might rely on "pointing" to another entity and store that entity inside them which can become annoying when dealing with serialization and deserialization.

The main problem is making sure that the entity that the deserialized component is pointing to is actually alive. This is not as much of a  problem when deserializing entire worlds since the world deserialization can just use the entities as offsets into the entity list it was given, but when deserializing a singular entity then there are no guarantees.

We might just be able to assume that the user checks for a correct entity (Or it uses `Option<Entity>` and defaults to `None` if the entity does not exist.)

**Comment by torkleyy** [comment]
There is actually more to that (as @Aceeri has already pointed out on Gitter):

* Basically, we'd like to be able to send entities over the network and also sync them
* However, in case somebody else creates an entity, how do you know that the other client doesn't have an entity with that id already?
* Just creating entities on the server is not an option, because it's both slow and you cannot have local entities
* Identification of the entities by string may solve the problem, but is too slow IMO

**Comment by Aceeri** [comment]
Could have some map of `u64` -> `Entity` for syncing purposes. The server could assign certain entities a server entity id on creation or whenever if the client allows for it.

**Comment by torkleyy** [comment]
@Aceeri Oh right, forgot to add that to my list. I think I found some issue with that but I don't know right now....

**Comment by Aceeri** [comment]
Expanding on this a bit:

Generations of entities should not be serialized. If deserialized into a new or existing world then that entity could either have already been destroyed (dead generation) or a generation that is exceeding the current generation of that index.

Instead it should just be the index of the entity and then checked on the world to get the current generation of that index or create a new entity either at that index or at the end of the current list of entities if the index exceeds the maximum entity.

For networking purposes I think you could have a syncing u32/u64 that the server would assign to an entity. As in the server would send to the client to create a new entity and assign some unique number to that entity which would allow them to communicate which entity they mean.

**Comment by Aceeri** [comment]
Related: https://github.com/serde-rs/serde/pull/909

**Comment by omni-viral** [comment]
[Here](https://github.com/amethyst/amethyst/pull/375) is some work related.

**Comment by omni-viral** [comment]
Now it is in #275

**Comment by torkleyy** [comment]
Okay, I think we solved most of this issue. The only thing that's left is the case where one component stores an entity. We'd have to replace that with a marker id, which sounds hard.

**Comment by omni-viral** [comment]
@torkleyy. You replace it in implementation of `SaveLoadComponent` for component that stores `Entity` from ids mapping provided into `save` funtion.

**Comment by torkleyy** [comment]
Huh, I guess that'd work since the blanket impl doesn't do that (`Entity` is not `Deserialize`). So we got that solved, thanks! Let's just add an example (either in docs or an extra file) before closing this issue.

**Comment by omni-viral** [comment]
> `Entity` is not `Deserialize`

This was the starting point of my implementation 😄

**Comment by torkleyy** [comment]
Well, is there anything we still need to do before closing this issue? Maybe better docs and book I'd say, but is there anything left to implement @Aceeri @omni-viral ?

**Comment by mhlakhani** [comment]
re: documentation - I'd really like to see an example/documentation of how to get saveload working if I do have a Component which stores an entity id. I saw some comments about it in the respective PR but looking at the code and comments I can't easily figure out how to do it

**Comment by torkleyy** [comment]
@mhlakhani Using the current master, you have to implement `SaveLoadComponent` (?) I think. There, you have a `save` function which has to return a serializable struct. So you'll define something like this:

```rust
#[derive(Serialize)]
pub struct ComponentSer<M> {
     // all the data fields
    entity_link: M,
}
```

(Sorry for the incomplete answer)

I'm currently working on an overhaul of the `saveload` module which will also include better docs.

**Comment by huin** [comment]
I'd like to add my own case of running into this issue to provide another perspective/use-case on it.

I've been wanting to serialize/deserialize `Entity` values inside components in a project I've been working on. The (potentially odd) thing I'm doing has a specs `World` running on a webserver, which then provides a JSON/REST API to read/write to the `World`.

I've currently got a set of types mirroring the component types purely for the purpose of serializing/deserializing, because any `Entity` value within them cannot be directly deserialized. This works, but is pretty cumbersome to maintain two sets of types, with conversion functions between them that work by maintaining a map from `Entity::id` to the corresponding `Entity`.

The serialization of the `Entity` includes both the `Entity::id` and the generation ID, so that dead entities are detected at deserialization time and not confused with an `Entity` by the same recycled ID. Both IDs are encoded as an opaque-to-the-API-client base64 blob.

**Comment by omni-viral** [comment]
@huin This approach you've described is basically the same as `specs::saveload` module uses.
