### ISSUE TITLE
More helpful error message when forgotten to register a component

### ISSUE THREAD

**Issue by kaedroho** [slide-rs/specs#196]
I added a new component to my project, but forgot to register it with ``World::register``. Then when I attempted to create an entity with that component, I was given the following error: "No resource with the given id"

I imagine this would be a common mistake for new users so perhaps it might be nice for usability to add a hint into that error message (Maybe something like: "No resource with the given id. Did you forget to register a component with `World::register<ComponentName>()`?").

**Comment by torkleyy** [comment]
@kaedroho That's a good idea, thanks for reporting!

If somebody is interested, here's how to solve that:

* Add `try_fetch` variants to [shred's `Resources`](https://github.com/slide-rs/shred/blob/master/src/res.rs#L175), returning an `Option` instead of panicking
* Call that method instead and panic in [`read_with_id`](https://github.com/slide-rs/specs/blob/master/src/world.rs#L467) / [`write_with_id`](https://github.com/slide-rs/specs/blob/master/src/world.rs#L478) with a more Specs-related message instead.
