### ISSUE TITLE
Add or remove components after entity creation

### ISSUE THREAD

**Issue by SirRade** [slide-rs/specs#207]
Forgive me if this is already stated somewhere, I was not able to find any information on it.

Is it possible to add to remove components dynamically to or from an entity after it has already been built?  
e.g.
```rust
let mut enemy = world.create_entity().with(Vel(2.0)).with(Pos(0.0)).build()
// freeze enemy
enemy.remove::<Vel>();
// give enemy laser
enemy.add(Laser(9999));
```

**Comment by torkleyy** [comment]
Hey there!

Since an entity is just an id (and a generational id), it does not contain any components. Those are actually stored in storages, so you'd get the storage (either with `World::write::<Vel>` or with `SystemData`) and then just call `.remove(entity)` on it.

For more questions, you may also want to join us on [Gitter](https://gitter.im/slide-rs/specs).

**Comment by SirRade** [comment]
Thank you very much for the insanely fast reply :)  
I will head over Gitter next time I have a question while exploring the crate.
