### ISSUE TITLE
Use HList for typechecked typemaps

### ISSUE THREAD

**Issue by Aceeri** [slide-rs/specs#235]
Instead of using a `TypeId` -> `T` map for resources and components, we could use a `HList` so you get compiletime errors if you forgot to register a resource or component, rather than a runtime error. Drawbacks of this is it becomes a bit more difficult to construct the type or "name" it.

**Comment by torkleyy** [comment]
> a bit more difficult

If we were to with zero type erasure and this approach, it would be super ugly to name the type itself (you would also have to change signatures as soon as you add another resource), so you'd generate a typedef. And another drawback is increased macro usage.

**Comment by Aceeri** [comment]
> And another drawback is increased macro usage.

With https://github.com/Sgeo/hlist rather than https://github.com/lloydmeta/frunk I don't think we'd need to include macros at least. I'm unsure as to whether we need that extra functionality that `frunk` has for this stuff.

**Comment by torkleyy** [comment]
If we don't have a macro, do you want the user to write

```rust
type MyWorld = World<Cons<Cons<Cons<Cons<Foo, Nil>, Bar>, Baz>, Qux>>;
```

?

**Comment by Aceeri** [comment]
Is there a case where that would even be useful though?

**Comment by torkleyy** [comment]
What exactly?

**Comment by Aceeri** [comment]
Specifying the world's type exactly I mean. In `impl` blocks for the `World` will just look like:
`impl<T> World<T> { ... }`. And most uses of the world will probably just use type inference rather than explicit typing.

**Comment by torkleyy** [comment]
Except when storing / passing it around?

**Comment by Aceeri** [comment]
I'm mostly assuming that things dealing with the `World` will just be using a generic.

**Comment by WaDelma** [comment]
If we only had working impl trait...

**Comment by torkleyy** [comment]
To sum up what I think about this:

* we can't make something like an `HList` the only way to define your resources. Otherwise there would be no runtime way to e.g. register `Component`s which is useful for scripting and also pure Rust code.
* that means we could implement this, and be generic over different `World` implementations. One major drawback is probably complexity.
* We'd have to create traits like `Retrieve<R>`, `R` being a resource type. The `HList` would only implement this trait for the types it contains, the current `World` for all `R: Resource`.

---

So I think it can be done in theory, I'm just unsure

1) how valuable the error messages are, also considering the better error message you added lately @Aceeri 
2) if the additional complexity is worth it

**Comment by Aceeri** [comment]
@torkleyy I don't think it is worth it right now, HLists are pretty unwieldy/annoying without some Rust features like impl Trait/specialization/etc.

**Comment by torkleyy** [comment]
This is outside of the scope of Specs; Specs will continue to just use a dynamic `World`.
