### ISSUE TITLE
Pass Component as Parameter

### ISSUE THREAD

**Issue by itmuckel** [slide-rs/specs#340]
I want to pass a component as a parameter to a function.

```rust
    pub fn new(world: &mut World, position: Point, graphics_id: u32, active: bool, comp: Box<Component>) -> EntityBuilder {
        create_basic_entity(world, position, graphics_id, z_index::SETTLER, 1.0)
            .with(ActiveSettler(active))
            .with(comp)
            .with(CurrentDestination(None))
    }

```

I get:

```
error[E0191]: the value of the associated type `Storage` (from the trait `specs::Component`) must be specified
 --> src\game\game_objects\settler.rs:9:94
  |
9 |     pub fn new(world: &mut World, position: Point, graphics_id: u32, active: bool, comp: Box<Component>) -> EntityBuilder {
  |                                  
```

I've read about associated types, but I cannot make it work. I feel like specs-rs is extremely generic and uses a lot of advanced features of Rust, so I cannot make much sense of the source. Any tipps?

**Comment by torkleyy** [comment]
You cannot pass a `Box<Component>`, because `Component` has an associated type. You would have to specify it like `Box<Component<Storage = DenseVecStorage<Mass>>>` but that's completely useless because it would only permit a `Mass` component. I recommend you use a type parameter like `new<C: Component>`.

**Comment by itmuckel** [comment]
Nice, that worked perfectly! Long live generics! 😄
