### ISSUE TITLE
What are the implications of the use of `unsafe` in this project? [question]

### ISSUE THREAD

**Issue by jcswart** [slide-rs/specs#342]
I'm new to rust.

I'm working on making a game and implementing my own ECS. I've recently come across this project and it looks awesome. My concern is that I don't understand the implications of the code around the uses of `unsafe`.

I'm worried this will lead to issues or non-idiomatic usage of the language. That said this project looks awesome and I'm most just curious as to the response as I know `unsafe` is often required to do things.

**Comment by WaDelma** [comment]
Biggest use of unsafe in `specs` are the underlying component storages.

Unsafe is used there because `specs` uses different datastructures in a sparse way: Entity is an index or key into the storage and it has or doesn't have certain component at particular moment of time.

This means that there are gaps in the datastructure that contain uninitialized memory which means that accessing the storage isn't safe without ensuring that the index/key actually has a value.

To ensure that there are actually value in the datastructure, a bitset is used which has bit set in entitys index if it has that component. When you iterate/join over component storages these bitsets are iterated/merged and components corresponding set bits are retrieved. When getting component for certain entity it's liveness is checked from `Allocator` which is responsible for creating/recycling removed entity ids and the bitset is checked that the entity actually has component.

Other use of unsafe is parallel joining which uses unsafe `DistinctStorage` to determine if backing storage is allowed to parallel join over.

**Comment by torkleyy** [comment]
When you use `unsafe` in a Rust library the idea is almost always to provide a safe wrapper around it, so it should be quite idiomatic. If you want to use this library, make sure to check out the book [here](https://slide-rs.github.io). For more questions you can always as [on our Gitter channel](https://gitter.im/slide-rs/specs).

**Comment by jcswart** [comment]
Thanks for the thoughtful responses!
