### ISSUE TITLE
Block-allocation of "component archetypes"

### ISSUE THREAD

**Issue by Zaerei** [slide-rs/specs#423]
Right now, each component has its own dedicated storage which you can choose based on various properties. This can help with things like cache-locality within the context of a single component, but a lot of times there are classes of components (say, Position, Velocity, and Shape) that will frequently be used together.

ECS systems often have a notion of "archetypes" which represent collections of components you usually want allocated together. Recently I believe Unity adopted this paradigm for their unveiled ECS functionality.

Note that this is not the same thing:

```rust
#[derive(Component)]
#[storage(...)]
struct A{...}

#[derive(Component)]
#[storage(...)]
struct B{...}

#[derive(Component)]
#[storage(...)]
struct C{...}

#[derive(Component)]
#[storage(...)]
struct Union{ a: A, b: B, c: C}
```

Because semantically your entity is not seen as having components `A`, `B`, or `C`, merely a component called `Union` that have members that merely look like `A`, `B`, and `C`. In fact, this sort of struct wrapping is commonly done to allow a single definition to be treated as different components!

The idea with an archetype is that the components may still be treated *as if* they are independent (that is, if an entity has a `Union` archetype, it can be treated as having `A`, `B`, and/or `C` in isolation).

Given what I know of specs internals, this is a tough problem but I think it should be possible. It may be possible to accomplish by allowing metadata for a component to contain a `stride` field which, pretending the component is accessed individually, shows how many bytes to skip in the target storage before re-downcasting to the actual type. Optimizing `join` to work easily when accesses over an entire archetype are performed at once may be impossible, however, or at least may require a slightly different API. (That is, allowing me to get `A`, `B`, and `C` in one read instead of 3 at different offsets).

In addition, the following properties probably need to hold to make this tractable:

1. An entity must have exactly 0 or 1 archetypes (could be extended in the future to allow >1 archetype provided their component sets are disjoint).
2. The entity's archetype, if any, must be declared at the time of construction
3. Any write to a component that belongs to the entity's archetype (if any) will write to the archetype storage at the appropriate entity location and bit offset of that component's memory location within the archetype.
4. Any read, similarly, reads from that location
5. Components in an archetype may not be deleted or inserted from the entity ("deletion" in an archetype would instead probably have to be accomplished by declaring the component as a Newtype around an `Option` or similar enum)
6. Other components may be written, read, inserted, and deleted as normal in their typical storages

If this is of interest I think this is a long-term goal. Allowing frequently used-together components to be stored together can help immensely with cache performance, but given we need parallel benchmarks (#27) this is at very earliest something to do after that, because without good benchmarks we can't measure what gains, if any, we'd get from it. We'd also need to communicate that you won't really see any improvement if your archetype components contain a lot of wrapper structures like `Vec` or `HashMap` (since only the pointers those collections hold would be near each other, not the actual data). But this is an issue even for the current system.

The other potential consideration for parallel performance is, since the components can be treated as disjoint, if two storages have `WriteStorage` references to two components within an archetype, you can get hella cache flailing as the two threads keep trying to write right next to each other in the same cache line. However, I think it's a worthwhile tool and I don't think the fact that it can be a performance footgun undermines the fact that it can be a huge performance boon when used properly. We could even provide a `world.disallow_archetype_concurrency` function or similar to cause the system to panic in these cases for debugging purposes.

(Aside: 3 and 4 obviously need special considerations for ZSTs but I don't think it's particularly much harder than handling ZSTs in any other data structure).

**Comment by torkleyy** [comment]
Sounds interesting, I haven't of this concept before. It also sounds rather comlex and not like a near-term goal, yeah. This is more like a 2.0 feature. I'll revisit this at a later point, but this could also work great as an experimental extension if you want to start working on it now.

**Comment by omni-viral** [comment]
As I understand components from archetype must be stored together for entities that contain that archetype and for entities that contain some of them anyway.
Because otherwise you would end up having duplicating storage for separate components and union with both will have huge holes in contiguous memory.

First thing one can replace `Storage` in API from concrete type to trait. Then it will be easier to experiment with different storage strategies.

**Comment by vblanco20-1** [comment]
Unity does not follow this paradigm. What unity does is that entities are stored in blocks by their component archetype, but thats allways.

If you have entity E1 with components A and B, and entity E2 with components BC, and entity E3 with components CD, you will have 3 blocks, one block for E1, other for E2, and other for E3. If you had E4 that was components A and B, it woulld get stored alongside E1. If you took E2 and removed the component C, then the block of entities with BC gets "deleted", and a new block with ONLY component C is allocated. Adding/removing a component from an entity is to "move" it into a different block and memcopying the components.

This is complicated, of course, but it has the best performance you can possibly get on an ECS, becouse doing the "join" operation is just finding the blocks that have the Join components, and iterating through their arrays, wich are perfectly contiguous. Becouse this is all on super basic arrays, its trivially parallelized.

**Comment by OvermindDL1** [comment]
As a note, the way I implemented my ECS is having a `required` declaration on components, so if Component B always requires Component A then when B is added then A is added too automatically, consequently the 'Union' above would just require the others.  It worked well for me, never really needed to mess with the design, and it was quite simple.

Also that Unity was doesn't sound very performant...  Maybe if you are iterating over joined types always but for mismatches it doesn't seem so.  I've always kept a single component type per table and just iterate across that, which allows for many kinds of optimizations like SSE instructions over position/movement tables among more, while keeping only the components you are accessing together in cache without a lot of extra unused things being uselessly loaded from RAM.

**Comment by vblanco20-1** [comment]
@OvermindDL1  the blocks keep "separated" arrays in the blocks. If a block has components A,B,C, they are stored as 3 contiguous arrays [AAAAA,BBBBB,CCCC], structure of arrays fashion.

**Comment by OvermindDL1** [comment]
What about when a system wants to access, say, just A and B components on all entities that have them?

**Comment by torkleyy** [comment]
I don't see that much of a gain here honestly. Do you have any benchmarks proofing the efficiency of this pattern? It would be helpful to discuss based on the numbers.

As for component dependency, that definitely is something I want to implement.

**Comment by vblanco20-1** [comment]
@OvermindDL1  it iterates over all the blocks and grabs the ones that do have A and B, then it updates the system. I dont know about the exact specifics. 
@torkleyy  ive tried to run complicated simulations on the fastest open source C++ ECS i know (Entt) and unity was faster while being C#. Faster in much more complicated simulations. But in those simulations/demos they have shown they have a fairly low-ish amount of different archetypes. I dont know how it performs if you have many different types of entities all with different component sets.

**Comment by OvermindDL1** [comment]
@vblanco20-1 That sounds pretty slow, especially compared to the method I built up over the years (which I still consider not the best style) where I built up aspect component lists to register (and as components were added/removed with entities then the entities would be added/removed to those interned lists that were shared across).

> ive tried to run complicated simulations on the fastest open source C++ ECS i know (Entt) and unity was faster while being C# (using their custom compiler). Faster in much more complicated simulations. But in those simulations/demos they have shown they have a fairly low-ish amount of different archetypes. I dont know how it performs if you have many different types of entities all with different component sets.

Oh now I'd love to test that, I never released my ECS as standalone (since it was very intertwined into my engine) but I'd love to see how those compare.  I definitely do not use a low amount of component types (I can well exceed thousands in a single game) with them being added and removed dynamically throughout an entity's lifetime and I still pushed hundreds of thousands to millions of such dynamic entities at 60fps+ depending on the system designs (I have this thing about creating little things with absolute *tons* of processing entities as I tend to like vast hoards in games, Factorio hits that itch quite well for example).

Having a low archetype count is entirely contrary to the designs I usually do, and most ECS's I've seen have very tight limits on component type counts (usually maxing out at ones as low as 64 to a couple hundred at most, where I use *significantly* more than that), so I'm curious how Unity's would handle this as well.

**Comment by vblanco20-1** [comment]
@OvermindDL1  now im very interested on what kind stuff you are doing. You say you are pushing hundreds of thousands of dynamic entities at 60fps? Thats what i was trying to do myself  here: http://victor.madtriangles.com/code%20experiment/2018/06/11/post-ecs-battle-huge.html (40.000 boids with a heavy separation kernel, and 130.000 total instanced rendered objects recalculating matrices per frame). Code is not public becouse at the moment its really messy.

**Comment by OvermindDL1** [comment]
Well in my case I tend to do 2D most often, so only needed 2 dimensions so that simplifies the matrix work, as well as the position/movement are often highly optimized by updating via eigen or opencl (a plus side of having things so ordered like that, I don't even things not calculating when not moving, their velocity is just zero'd then), usually the most things on screen at a time is a few thousand at most (into array indexed chunks for fast rendering lookups, those chunks being another component table with unique storage for this purpose), they are self-driven so simple state updates without worrying about user inputs (user interacts in other ways), etc...  The systems other than movement handling are generally more sporadic, a lot of sleeping depending on the systems while being distributed across CPU cores and only running when there is work or on intervals or other delays.  My controls/inputs are part of my node system and not in the ECS directly for note.  I keep hoping for amethyst to replace my old engine because it is filled with so much cruft over the decades that it is just hard to update anymore (the eigen integration was one of the more recent major changes made)...  ^.^;

**Comment by torkleyy** [comment]
I'm currently implementing this for https://gitlab.com/nitric/nitric so "component classes" can be created which group components together as you described. 

This out of scope for Specs, but it's been a helpful discussion for nitric. I'll thus close this issue.

**Comment by vblanco20-1** [comment]
@torkleyy  you can have a look at "decs", from my profile. I implemented those "block archetypes", with custom memory management and all. The speed it gets is unmatched anywhere, and all on perfect SoA layout.
