### ISSUE TITLE
The coveralls.io badge is out of date

### ISSUE THREAD

**Issue by andreivasiliu** [slide-rs/specs#430]
Not sure if it's an intentional/known issue (if it is feel free to close this), but I noticed that the '90% coverage' badge on the `README.md` file shows coverage for a commit from 2017.

It seems Coveralls is not aware of any recent builds:
https://coveralls.io/github/slide-rs/specs?branch=master

**Comment by torkleyy** [comment]
Yeah, I think the coverage failed to build the report correctly, I don't remember. The coverage wasn't really a good measurement anyway.

**Comment by andreivasiliu** [comment]
Okay, I'll leave it up to you on whether to fix/remove/keep the badge. I personally think it's a good tool for those who want to write tests.

**Comment by torkleyy** [comment]
> I personally think it's a good tool for those who want to write tests.

I had the integration enabled, but it was really weird because it also counted lines with comments or docs. So the test failed because the coverage randomly decreased. I think having branch coverage would be a lot better than line coverage, but I don't know how to do it / don't have time for it.

@slide-rs/core What do we do about the badge?

**Comment by WaDelma** [comment]
As it doesn't actually reflect what's going on, I would just remove it.
If we can get it working properly then it would be good (I would prefer badge for mutation testing, but that's another whole topic).
