### ISSUE TITLE
Needs more docs

### ISSUE THREAD

**Issue by svenstaro** [slide-rs/specs#48]
So I'm currently trying to use this but I would really like to get some more docs on things. For instance, what does `add_system` do exactly and how do I use it? What are the differences between anonymous systems and named system and use cases for each? Is it even a good idea to use the anonymous systems?

**Comment by kvark** [comment]
@svenstaro so `Planner` has a list of systems ("named" systems). By calling `add_system` you populate this list. Systems from the list are executed each time you call `dispatch`. In contrast, anonymous `run*` calls are executed once and never stored anywhere. I'm curious to see myself where these `run*` calls can fit nicely.

For an example of how to use `specs` at scale, please see [yasteroids](https://github.com/kvark/yasteroids). The [game](https://github.com/kvark/yasteroids/blob/master/src/game.rs) module contains systems creation and execution.

**Comment by svenstaro** [comment]
Thanks a lot for your link, that is extremely helpful in trying to understand how you intend this library to be used. I still would like to request more docs at this repo as it's the most obvious place to look. As an inspiration on what the docs might look like, perhaps take a look at the excellent [EntityX](https://github.com/alecthomas/entityx) which is an ECS I used before and I think its docs are quite good (while succinct).

**Comment by kvark** [comment]
I agree, we'll not close this issue until the proper docs are in place.

**Comment by mrZalli** [comment]
I've had similar problems, but luckily the code is readable and easily understandable.

**Comment by serprex** [comment]
A less abstract example would be nice too. On that front I'm working on a roguelike: https://github.com/serprex/rg

I'll see if I come up with some ideas on actual documentation as I experiment; I'ven't any previous experience with an ecs

**Comment by sinesc** [comment]
I'd also like to point out that the meaning of runXwYr is not entirely obvious: I've just paid a visit to impl_run to get it :)

**Comment by kvark** [comment]
I'm thinking if `runXwYr` should be killed completely

**Comment by serprex** [comment]
+1 for getting rid of runwr, implementing it manually in run_custom makes it much clearer what's happening

**Comment by kvark** [comment]
Interesting idea about the `fetch!` macro! :+1:

**Comment by bzar** [comment]
Is this where we suggest topics for documentation? Might I suggest a better description on how to create and destroy entities dynamically? I'm trying this library out by making a Space Invaders clone, and so far enything dynamic depending on component states quickly seems to become verbose.

The basic case I've reached is creating a "shot" entity when the a player wants to and can shoot, which should have a position based on the player's position and an attached lifetime. When that lifetime is reduced to zero, the shot should self-destruct. This is, I think, something akin to a lithmus test for dynamic object creation/destruction.

The first case has a small catch, where the shot cannot actually be entirely created while iterating the (player, position)-join, since the position is already borrowed by the iterator to get the player position. This can be worked around by storing information for shots to create in a separate data structure, which is then iterated through to create the shots. It is, however, a bit ugly and allocates memory for little gain.

The second case I'm not sure how to implement. I didn't find any way to map from a component back to its entity, so I can't really process lifetimed entities separately. Should I just iterate all entities and check if they have a lifetime? This seems somewhat verbose and inefficient.

Attached below is some code demonstrating these wrinkles. A lot in it is placeholder (like sprites having just a color), but it should suffice as an example for discussion.

    planner.run_custom(|arg| {
        // This is a lot of locking to do each time for the small possibility of a shot being fired
        let (mut s_player, mut s_shot, mut s_velocity, 
             mut s_position, mut s_lifetime, mut s_sprite) = arg.fetch(|w| {
            (w.write::<Player>(),
            w.write::<Shot>(),
            w.write::<Velocity>(),
            w.write::<Position>(),
            w.write::<Lifetime>(),
            w.write::<Sprite>())
        });

        for (player, velocity) in (&s_player, &mut s_velocity).iter() {
            if player.left_pressed == player.right_pressed {
                velocity.0.x = 0;
            } else if player.left_pressed {
                velocity.0.x = -1;
            } else {
                velocity.0.x = 1;
            }
        }

        // Temporary data structure for shots to create
        let mut shot_positions = Vec::new();

        for (player, position) in (&mut s_player, &s_position).iter() {
            if player.fire_cooldown > 0 {
                player.fire_cooldown -= 1;
            }

            if player.fire_pressed && player.fire_cooldown <= 0 {
                player.fire_cooldown = 30;
                shot_positions.push(position.0);
            }
        }

        // Create the shots
        for position in shot_positions {
            let shot = arg.create();
            s_shot.insert(shot, Shot);
            s_lifetime.insert(shot, Lifetime(100));
            s_sprite.insert(shot, Sprite(Color::RGB(255,0,0)));
            s_position.insert(shot, Position(position));
            s_velocity.insert(shot, Velocity(Vector2::new(0, -2)));
        }
    });

    planner.run1w1r(|p: &mut Position, v: &Velocity| {
        p.0 += v.0;
    });

    planner.run1w0r(|l: &mut Lifetime| {
        l.0 -= 1;
        // How do I remove the entity here?
    });

**Comment by sunjay** [comment]
It would be nice to have a tutorial that runs through using an ECS for those of us that aren't as familiar. Basically just a walk through of an entire example of using specs: creating some basic components and systems, tying then together and then running everything.

**Comment by vitvakatu** [comment]
@sunjay I'm afraid we don't have enough time to create a tutorial for now.
You can look through [yasteroids](https://github.com/kvark/yasteroids) or [ecs subsystem of amethyst](https://github.com/amethyst/amethyst/tree/develop/src/ecs) to get basic information about usage. 
I'll try to write something like tutorial in a week or so.

**Comment by torkleyy** [comment]
We have documentation for every item and we got a book with tutorials recently. "Examples for every public item" is tracked by #145. Closing.
