### ISSUE TITLE
Aspects

### ISSUE THREAD

**Issue by kvark** [slide-rs/specs#51]
Aspect is basically the configuration of components that are being read or write by a particular system. It's an additional concept to work with, but it has a strong benefit: static knowledge about the system dependencies. With that information given, we can safely know in advance if two systems are compatible to work in parallel or not. Thus, we can schedule them more effectively.

Essentially, aspects would allow us to get rid of the `RwLock` (even though I consider their usage to be rather elegant as it stands now), since we would already know when something is available. Also, seems like it would benefit from directly controlling the threads instead of using `thread_pool` (#42).

If we go further, we can cache entity lists per aspect as proposed by @OvermindDL1. This could be a replacement for our current `BitSet`-based system.

All in all, this is just something to think about. It seems like introducing `Aspect` would essentially drive the architecture in a different direction, so deserves to live in a separate project.

**Comment by OvermindDL1** [comment]
My take on Aspects (proven quite efficient for me in the past, though this mock-up is still being optimized so ignore the couple of highly inefficient loops that can be fairly easily fixed...):  https://github.com/OvermindDL1/OverECS/blob/master/main.cpp

**Comment by torkleyy** [comment]
@OvermindDL1 Could you please explain how you're using the information provided by aspects in order to gain performance benefits? More specifically, even though we can know which systems are compatible to run in parallel, we don't exactly know when we may run the next system (we had to wait for a whole set of systems to finish if we want to be sure).

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Could you please explain how you're using the information provided by aspects in order to gain performance benefits? More specifically, even though we can know which systems are compatible to run in parallel, we don't exactly know when we may run the next system (we had to wait for a whole set of systems to finish if we want to be sure).

Internally at world startup (I required all systems to be registered ahead of time, though could be enabled/disabled) I built up a tree of run order and just greedily grabbed systems from the tree to run their update calls.  Branches in a tree could not go 'up' until the previous layer of those nodes were done, but other nodes could go up fine if they completed first.  It was pretty simple but it worked well for me.  I did not show off the 'optional' components that a system might access in my example above but those were used in the tree so optional's counted as full access, even though they were not touched for the family/cache registration.

**Comment by torkleyy** [comment]
@OvermindDL1

So you store a topological sort of the systems in order to estimate which system is likely to be executed next? And additionally a graph for actually checking this?

**Comment by OvermindDL1** [comment]
@torkleyy It is generated at runtime on load since I may not know the systems I'll be loading in to the world at compile-time, but I do know what I will be loading in by the time I instance the world.  It is a topological sort though, with an 'end-node' to handle special events (my systems can be set to read only from a components so they can run concurrently with others that read only, but I have a lot of mine do that but instead send 'changesets' to another system that is processed at the end of all the other to run a callback to to make actual changes after checking that the preconditions are met, this is a pretty complex part of mine that you have to be careful to get right so it is only used for certain kind of trivially parallizable areas).

And yes, it is NP-complete, just cache it on world/ecs load and only read it from then-on out.  It does not always generate the 'best' tree, but I have not really cared enough to fix that.
