### ISSUE TITLE
Idiomatic way to limit amount of entities in the world?

### ISSUE THREAD

**Issue by Abendstolz** [slide-rs/specs#516]
Hello!

Before I dive into the problem at hand, let me say **thank you**!
Working with specs is awesome! A few years back I had started to write my own ecs (in C++ back then), but although it was tailored to my exact needs, specs beats it by leagues!

Thank you for doing the hard work!
-----
My Problem
-----
I want to limit the amount of entities in the world.

Now for my hacky attempt (first time playing around with specs) I created a resource that holds a count of entities within the world.
Whenever the user (or a spawner system) spawns another entity, the count goes up.
Whenever an entity is killed (by another system), the count goes down.

This doesn't work really well (my unproved assumption is: due to parallelism). In fact I had to guard the `u16` that represents the number of entities in the world during deletion of entities, else I would get a panic at runtime after the first entity is spawned, because it (the u16) tried to go negative.

Now I can share the relevant parts of the code, but I wanted to ask whether there is an idiomatic way I missed by only partially digging through all of the examples.
I couldn't find a way to read the count of entities from `Entities` and also I am not sure it's accurate before `maintaining`.

Anyway, here is the code:
 
Maybe I am missing something totally obvious, like having to switch the order of `maintain()` with something else?

the main world-loop:

```rust
pub fn update(&mut self, gfx: &mut Gfx) -> () {
    use crate::gfx::resources::mesh::create_cube_mesh;

    self.ecs_dispatcher.dispatch(&self.ecs_world.res);
    self.ecs_world.maintain();

    let entities_in_world: u16 = self.ecs_world.read_resource::<EntitiesInWorld>().0;
    debug!(self.logger, "entities in world {}", entities_in_world);

    if entities_in_world < self.max_entities_in_world.into() {
        let entities_to_spawn = self.find_entities_to_be_spawned(gfx);
        debug!(self.logger, "entities to spawn: {}", entities_to_spawn.len());
        for (position, mesh_id) in entities_to_spawn {
            debug!(self.logger, "creating mob!");
            self.create_mob(&position, create_cube_mesh(1.0), gfx);
        }
    }
    self.clear_entities_to_spawn();
    self.update_entity_rendering();
}
```

the initialization of the (sp)ecs part of the world:

```rust
        ecs_world.register::<PositionComponent>();
        ecs_world.register::<VelocityComponent>();
        ecs_world.register::<SpawnerComponent>();

        ecs_world.add_resource(EntitiesToSpawn(Vec::new()));
        ecs_world.add_resource(EntitiesInWorld(0));

        let ecs_dispatcher = EcsDispatcherBuilder::new()
            .with(DeleteFarAwayNpcSystem, "DeleteFarAwayNpcSystem", &[])
            .with(SpawnNpcSystem, "SpawnNpcSystem", &["DeleteFarAwayNpcSystem"])
            .with(UpdatePositionSystem, "UpdatePositionSystem", &["SpawnNpcSystem"])
            .build();
```
and the systems:

```rust
pub struct SpawnNpcSystem;

impl<'a> System<'a> for SpawnNpcSystem {
    type SystemData = (ReadStorage<'a, Position>,
                       ReadStorage<'a, SpawnerComponent>,
                       Write<'a, EntitiesToSpawn>,
                       Write<'a, EntitiesInWorld>);

    fn run(&mut self, (positions, spawners, mut entities, mut entities_in_world): Self::SystemData) -> () {
        use specs::Join;

        for (position, spawner) in (&positions, &spawners).join() {
            entities.0.push(SpawnedEntity { position: position.0.clone(), mesh_id: Some(0) });
            entities_in_world.0 += 1;
        }
    }
}

pub struct DeleteFarAwayNpcSystem;

impl<'a> System<'a> for DeleteFarAwayNpcSystem {
    type SystemData = (ReadStorage<'a, Position>,
                       ReadStorage<'a, SpawnerComponent>,
                       Write<'a, EntitiesInWorld>,
                       Entities<'a>);

    fn run(&mut self, (positions, spawners, mut entities_in_world, mut entities): Self::SystemData) -> () {
        use specs::Join;

        for (position, (), entity) in (&positions, !&spawners, &entities).join() {
            if position.0.x.abs() > 20.0 || position.0.y.abs() > 20.0 || position.0.z.abs() > 20.0 {
                entities.delete(entity).expect("Couldn't delete entity");
                if entities_in_world.0 > 0 {
                    entities_in_world.0 -= 1;
                }
            }
        }
    }
}
```

**Comment by torkleyy** [comment]
Hello, I'm glad you enjoy Specs.

> I want to limit the amount of entities in the world.

Interesting, that's a case I've not heard of yet.

Looking at your code, the problematic lines are in `DeleteFarAwayNpcSystem`:

```rust
entities.delete(entity).expect("Couldn't delete entity");
if entities_in_world.0 > 0 {
    entities_in_world.0 -= 1;
}
```

Entities deleted using [`EntitiesRes::delete`](https://github.com/slide-rs/specs/blob/384b4d044df12cb778ba8fe42974c7b4dce07e53/src/world/entity.rs#L296) get only marked for deletion; that means they can still be joined over (basically they exist for the rest of the frame, and get deleted at the end). That means you can delete the same entity twice like that, the real entity count will decrease only by one but your counter goes down by two.

I think this is best solved by exposing some additional API from Specs (also, I should probably expand the docs on this). I can imagine:

* `EntitiesRes::is_flagged` returning a `bool` whether or not an entity is flagged for deletion
* `EntitiesRes::num_entities`

I think both would be valuable to have for your case, even though the last one is enough to cover it.

As for the implementation, the first one can simply perform a load on the respective bit in `alloc.killed`.

The `num_entities` method might be a bit trickier depending on how fast it should be. The potential issues are:

* we can only get a snapshot of the active entities
* ideally, we should perform a parallel bit set count instead of counting iteration elements; such a function can be found in `hibitset/util.rs`, but I don't think it's exposed yet
* it's unclear whether flagged entities should be taken into account for this

Depending on your exact requirements, you might not want to track the global count, but instead only the count allocated by a specific (group of) systems, and only limit those. In that case you'd have to guard against the case where an entity is flagged twice.

**Comment by Abendstolz** [comment]
@torkleyy Thanks a bunch for taking the time to explain.

**Comment by lanedraex** [comment]
Hey @Abendstolz the way I solved a problem similar to yours was by creating a GC system.

Every time, let's say an NPC, is killed, it's marked with a GC component, and then the GC system loops through all these and deletes them.
