### ISSUE TITLE
Get All Storages from World

### ISSUE THREAD

**Issue by ducharmemp** [slide-rs/specs#559]
Related to: https://github.com/slide-rs/specs/issues/462, https://github.com/slide-rs/specs/issues/362, https://github.com/slide-rs/specs/issues/310

So I've spent time browsing the previous issues and I know that scripting is a complex topic, but I have some code that already achieves some of this it's just not as nice as I could make it just yet. So essentially, my script system in a nutshell can construct values to/from my scripting language, but there is a bit of boilerplate code to specify exactly all of the component storages needed and to set up the code to convert from/to. In pseudocode, I'd like some ability to do the following in pseudocode:
```rust
for each entity in entities {
    for each storage in world.storages {
        let component_ref = storage.get(entity);
        // Convert from/to lua here
    }
```

I don't really need the ability to dynamically get any component from an entity, since I'll know ahead of time from my script *what* components to look at specifically. I tried playing around with trait objects but it seems like the type system really won't let me mess with it too much. Any thoughts or pointers? The way I'm doing it is fine but brittle and I'm fairly forgetful.

**Comment by DefecateRainbows** [comment]
I also need to do this. I was digging around in the source for specs, looking for somewhere where a list of the resources (because storages are really just a specific type of resource) are found.
I found this. https://docs.rs/shred/0.7.1/src/shred/res/mod.rs.html#114-116
I'm just going to change my local source to make public, and then I'll be able to access it via world.resources.resources, then I'm good to go.
If you didn't want to change your local source, you could transmute (https://blog.knoldus.com/safe-way-to-access-private-fields-in-rust/) or find some other way to to manipulate the field.
Alternatively, we could PR shred asking for this field to be made public or at least to have getters/setters available.
